library(shiny)
library(reshape2)
library(gridExtra)
library(ggplot2)
library(plyr)
library(scales)

load_df <- function(Rfile){
  df <- source(Rfile)
  df <- as.data.frame(df[1])
  names(df) <- gsub("value.","",names(df))
  return (df)
}

leads <- load_df('Leads.R')
sales <- load_df('SO.R')

shinyServer(function(input, output,session) {

   
   observe({
   updateSelectInput(session,inputId = "y.factor" ,label = 'sales_rep'
                       ,choices = unique(as.character(leads$Lead.Generator[leads$segment==input$segment]))
                       ,selected = "E0063 Rena Wong")
     
   })

   output$LeadsPlot <- renderPlot({
    environment<-environment()
    data=subset(leads,Lead.Generator==input$y.factor)
    leads = subset(data,as.Date(as.character(Date.Created)) >= input$dateRange[1]&as.Date(as.character(Date.Created)) <= input$dateRange[2])
    p <- ggplot(leads,aes(x=Date.Created, y=freq)
                ,environment = environment)
    p <- p+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Leads Generated by",input$y.factor))+
      xlab("Day")+
      ylab("No of Leads")+
      scale_x_datetime(breaks = date_breaks("1 day"))+theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p
  })
   
  output$LeadsPlot_by_week <- renderPlot({
    environment<-environment()
    leads$week <- as.numeric( format(leads$Date.Created+3, "%U"))
    data <- subset(leads,trimws(Lead.Generator,"both")==input$y.factor)
    data.week <- aggregate(data$freq, by = list(data$week),FUN = sum)
    p1 <- ggplot(data.week,aes(x=data.week[,1], y=data.week[,2])
                 ,environment = environment)
    p1 <- p1+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Leads Generated by",input$y.factor))+
      xlab("Week")+
      ylab("No of Leads")+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p1
  })
  
  output$SalesPlot <- renderPlot({
    environment<-environment()
    data=subset(sales,Sales.Rep.1==input$y.factor)
    sales.day <- aggregate(data$Maximum.of.Amount..Net.of.Tax.,by = list(data$Date.Created),FUN = sum)
    p <- ggplot(sales.day,aes(x=sales.day[,1], y= sales.day[,2])
                ,environment = environment)
    p <- p+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Sales Generated by",input$y.factor))+
      xlab("Day")+
      ylab("Sales Amount")+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p
    
  })
  
  output$LeadsTable <- renderDataTable({
    LeadsTable <- aggregate(leads$freq,by = list(leads$Lead.Generator,leads$segment),FUN = sum)
    names(LeadsTable) <- c("Sale_rep","segment","No of Leads")
    LeadsTable
 })
  output$SalesTable <- renderDataTable({
    SalesTable <- aggregate(sales$Maximum.of.Amount..Net.of.Tax.,by = list(sales$Sales.Rep.1,sales$segment),FUN = sum)
    names(SalesTable) <- c("Sale_rep","Segment","Sales_Amount")
    SalesTable
    
  })
  
 })