library(shiny)
library(reshape2)
library(gridExtra)
library(ggplot2)
library(plyr)
library(scales)
shinyServer(function(input, output,session) {
   df <- source('Leads.R')
   df <- as.data.frame(df[1])
   names(df) <- c("Date.Created","Lead.Generator","segment", "freq")
   
   observe({
   updateSelectInput(session,inputId = "y.factor" ,label = 'sales_rep'
                       ,choices = unique(as.character(df$Lead.Generator[df$segment==input$segment]))
                       ,selected = "E0063 Rena Wong")
     
   })

   output$LeadsPlot <- renderPlot({
    environment<-environment()
    data=subset(df,Lead.Generator==input$y.factor)
    df = subset(data,as.Date(as.character(Date.Created)) >= input$dateRange[1]&as.Date(as.character(Date.Created)) <= input$dateRange[2])
    p <- ggplot(df,aes(x=Date.Created, y=freq
                       ,group=Lead.Generator,color=Lead.Generator)
                ,environment = environment)
    p <- p+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Leads Generated by",input$y.factor))+
      xlab("Day")+
      ylab("No of Leads")+
      scale_x_datetime(breaks = date_breaks("1 day"))+theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p
  })
   
  output$LeadsPlot_by_week <- renderPlot({
    environment<-environment()
    df$week <- as.numeric( format(df$Date.Created+3, "%U"))
    data <- subset(df,trimws(Lead.Generator,"both")==input$y.factor)
    data.week <- aggregate(data$freq, by = list(data$week),FUN = sum)
    p1 <- ggplot(data.week,aes(x=data.week[,1], y=data.week[,2]),environment = environment)
    p1 <- p1+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Leads Generated by",input$y.factor))+
      xlab("Week")+
      ylab("No of Leads")+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p1
  })
  
  output$LeadsTable <- renderDataTable({
    df <- aggregate(df$freq,by = list(df$Lead.Generator),FUN = sum)
    names(df) <- c("Sale_rep","No of Leads")
    df
 }, options = list(lengthMenu = c(5, 10, 15), pageLength = 5))
  
 })