library(shiny)
library(reshape2)
library(gridExtra)
library(ggplot2)
library(plyr)
library(scales)

load_df <- function(Rfile){
  df <- source(Rfile)
  df <- as.data.frame(df[1])
  names(df) <- gsub("value.","",names(df))
  return (df)
}

leads <- load_df('Leads.R')
sales <- load_df('SO.R')

shinyServer(function(input, output,session) {
  SalesTable <- aggregate(sales$Maximum.of.Amount..Net.of.Tax.,by = list(sales$Sales.Rep.1,sales$segment),FUN = sum)
  names(SalesTable) <- c("Sale_rep","Segment","Sales_Amount")
  LeadsTable <- aggregate(leads$freq,by = list(leads$Lead.Generator,leads$segment),FUN = sum)
  names(LeadsTable) <- c("Sale_rep","segment","No of Leads")
  SalesTable_No <- aggregate(sales$Event.Name,by = list(sales$Sales.Rep.1,sales$segment),FUN = length)
  SalesTable$No_of_Sales <- SalesTable_No[,3]


   observe({
   updateSelectInput(session,inputId = "y.factor" ,label = 'sales_rep'
                       ,choices = unique(as.character(leads$Lead.Generator[leads$segment==input$segment]))
                       ,selected = "E0063 Rena Wong")
   })
   observe({
     updateSelectInput(session,inputId = "sales_rep" ,label = 'sales_rep'
                       ,choices = unique(as.character(leads$Lead.Generator[leads$segment==input$segment_sale]))
                       ,selected = "E0063 Rena Wong")
   })

   output$LeadsPlot <- renderPlot({
    environment<-environment()
    data=subset(leads,trimws(Lead.Generator,"both")==input$y.factor)
    leads = subset(data,as.Date(as.character(Date.Created)) >= input$dateRange[1]&as.Date(as.character(Date.Created)) <= input$dateRange[2])
    leads$week <- as.numeric( format(leads$Date.Created+3, "%U"))
    data.week <- aggregate(leads$freq, by = list(leads$week),FUN = sum)
    
    switch(input$plotty,
           "week" = {aesthetics1 = aes(x=data.week[,1], y=data.week[,2])
           data = data.week
           xlabtxt = "Week"},
           "day"  = {aesthetics1 = aes(x=Date.Created, y=freq)
           data = leads
           xlabtxt = "Day"}

    )
    p <- ggplot(data,aesthetics1
                ,environment = environment)
    p <- p+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Leads Generated by",input$y.factor))+
      xlab(xlabtxt)+
      ylab("No of Leads")+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p

  })
   
  
  output$SalesPlot <- renderPlot({
    environment<-environment()
    sales = subset(sales,as.Date(as.character(Date.Created)) >= input$dateRange_sale[1]&as.Date(as.character(Date.Created)) <= input$dateRange[2])
    data=subset(sales,Sales.Rep.1==input$sales_rep)
    sales.day <- aggregate(data$Maximum.of.Amount..Net.of.Tax.,by = list(data$Date.Created),FUN = sum)
    
    data$week <- as.numeric( format(data$Date.Created+3, "%U"))
    sales.week <- aggregate(data$Maximum.of.Amount..Net.of.Tax.,by = list(data$week),FUN = sum)
    
    switch(input$plotty_sale,
           "week" = {aesthetics1 = aes(x=sales.week[,1], y= sales.week[,2])
           data = sales.week
           xlabtxt = "Week"},
           "day"  = {aesthetics1 = aes(x=sales.day[,1], y= sales.day[,2])
           data = sales.day
           xlabtxt = "Day"}
           
    )
    p <- ggplot(data,aesthetics1
                ,environment = environment)
    p <- p+ geom_line(size = 1.5)+geom_point(size=4, shape=21, fill="white")+
      ggtitle(paste("Sales Generated by",input$sales_rep))+
      xlab(xlabtxt)+
      ylab("Sales Amount")+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    p
    
  })
  

  
  output$LeadsTable <- renderDataTable({

    LeadsTable
 })

  output$SalesTable <- renderDataTable({

    SalesTable
    
  })
  
  output$downloadSales <- downloadHandler(
    filename = function(){
      paste('sales','.csv',sep='')
      },
    content = function(file){
      write.csv(SalesTable,file)
      }
  )
  output$downloadLeads <- downloadHandler(
    filename = function(){
      paste('Leads','.csv',sep='')
    },
    content = function(file){
      write.csv(LeadsTable,file)
    }
  )
  
 })